#!/bin/sh

currdir=`dirname $0`
cd ${currdir}
killall audio_test 1>/dev/null 2>/dev/null
echo "TEST AUDIO LINE1:"
echo ""
echo "Now test LINE1 audio input, please connect cable to LINE1 input"
echo "(Rear-panel audio input on column 3 from left)"
./audio_test -iline1

