#!/bin/sh

currdir=`dirname $0`
cd ${currdir}
killall audio_test 1>/dev/null 2>/dev/null
echo "TEST AUDIO LINE2:"
echo ""
echo "Now test LINE2 audio input, please connect cable to LINE2 input"
echo "(Rear-panel audio input on column 5 from left)"
./audio_test -iline2

