#!/bin/sh

currdir=`dirname $0`
cd ${currdir}
killall audio_test 1>/dev/null 2>/dev/null
echo "TEST AUDIO LINE3:"
echo ""
echo "Now test LINE3 audio input, please connect cable to LINE3 input"
echo "(Front-panel audio input)"
./audio_test -iline3

